# Generated by Django 2.2.10 on 2020-02-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data_source', models.CharField(max_length=255)),
                ('campaign', models.CharField(max_length=255)),
                ('clicks', models.PositiveIntegerField()),
                ('impressions', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
